routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'FrontWebController@inicio')->name('inicio');
Route::get('inicio', 'FrontWebController@inicio')->name('inicio');
Route::get('noticia/{slug}', 'FrontWebController@noticia')->name('noticia');
Route::get('zonaideal', 'FrontWebController@zonaIdeal')->name('zonaIdeal');
Route::post('documentos', 'FrontWebController@solicitudDocumentos')->name('documentos');


Route::get('nosotros', function () {
    return view('nosotros');
});

Route::get('contacto', function () {
    return view('contacto');
});

Route::middleware('auth')->prefix('panel')->group(function(){
    Route::get('/', function(){
        return view('panel.panel');
    })->name('panel.inicio');

    Route::middleware('admUsuarios')->group(function(){
        Route::resource('usuarios', 'UsersController', ['except' => [ 'show', 'destroy' ]]);
        Route::get('usuarios/{id}/eliminar', 'UsersController@destroy')->name('usuarios.destroy');

        Route::resource('slider', 'SliderController', ['only' => ['index', 'edit', 'update']]);
    });

    Route::middleware('admNoticias')->group(function(){
        Route::resource('noticias', 'NoticiasController', ['except' => [ 'show', 'destroy' ]]);
        Route::get('noticias/{id}/eliminar', 'NoticiasController@destroy')->name('noticias.destroy');
    });

    Route::middleware('admAgenda')->group(function(){
        Route::resource('agenda', 'AgendaController', ['except' => [ 'show', 'destroy' ]]);
        Route::get('agenda/{id}/eliminar', 'AgendaController@destroy')->name('agenda.destroy');
    });

    Route::middleware('admBiblioteca')->group(function(){
        Route::resource('biblioteca', 'BibliotecaController', ['except' => [ 'show', 'destroy' ]]);
        Route::get('biblioteca/{id}/eliminar', 'BibliotecaController@destroy')->name('biblioteca.destroy');
        Route::post('select-ajax', ['as'=>'select-ajax','uses'=>'BibliotecaController@selectAjax']);

        Route::resource('materias', 'MateriasController', ['except' => [ 'show', 'destroy' ]]);
        Route::get('materias/{id}/eliminar', 'MateriasController@destroy')->name('materias.destroy');
    });

    Route::get('docs', function(){
      return view('panel.documentacion');
    })->name('docs');
});

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
// Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
// Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');
Route::get('/home', 'HomeController@index')->name('home');

app/Noticia.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;

class Noticia extends Model
{
	use Sluggable;

	public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'titulo'
            ]
        ];
    }


    protected $table = 'noticias';

    protected $fillable = ['titulo', 'resumen', 'contenido', 'urlImg', 'user_id'];

    public function user(){
    	return $this->belongsTo('App\User');
    }

    public function scopeBuscar($query, $titulo){
        return $query->where('titulo', 'LIKE', "%$titulo%");
    }
}

app/Http/Controllers/NoticiasController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Noticia;
use Image;

class NoticiasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $noticias = Noticia::orderBy('id', 'DSC')->paginate(20);
        return view('panel.noticias.index')->with('noticias', $noticias);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('panel.noticias.crear');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        

        $noticia = new Noticia($request->all());
        $noticia->user_id = Auth::User()->id;

        if($request->file('urlImg')){
            $file = $request->file('urlImg');
            $name = Auth::user()->id . '_' . time() . '.' . $file->getClientOriginalExtension();
            $url = '/img/noticias/'. $name;
            $path = public_path($url);
            $image = Image::make($file)->save($path);
            $noticia->urlImg = $name;
        }

        $noticia->save();

        alert()->success('<span class="green-text bold">'.$noticia->titulo.'</span> se ha creado' ,'Noticia Creada Exitosamente')->html()->persistent();

        return redirect()->route('noticias.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $noticia = Noticia::find($id);
        return view('panel.noticias.editar')->with('noticia', $noticia);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $noticia = noticia::find($id);
        $oldname = $noticia->urlImg;
        $noticia->fill($request->all());

        if($request->file('urlImg')){
            unlink(public_path('img/noticias/' . $oldname));
            $file = $request->file('urlImg');
            $name = Auth::user()->id . '_' . time() . '.' . $file->getClientOriginalExtension();
            $url = '/img/noticias/'. $name;
            $path = public_path($url);
            $image = Image::make($file)->save($path);
            $noticia->urlImg = $name;
        }       
        
        $noticia->save();

        alert()->success('Noticia: <span class="green-text bold">'.$noticia->titulo.'</span> fue editado' ,'¡Noticia Editada!')->html()->persistent();

        return redirect()->route('noticias.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $noticia = Noticia::find($id);
        if(!is_null($noticia->urlImg)){
            unlink(public_path('img/noticias' . $noticia->urlImg));    
        }        

        alert()->error('Noticia: <span class="red-text bold">' . $noticia->titulo . '</span> fue eliminada', '¡Noticia Eliminada!')->html()->persistent("Ok");

        $noticia->delete();
        return redirect()->route('noticias.index');
    }
}

resources/views/panel/noticias/crear.blade.php
@extends('panel.layouts.main')

@section('titulo')
	Crear Noticia
@endsection

@section('contenido')
<div class="contenedor">
	<div class="row card center-align">
		{!! Form::open(['route' => 'noticias.store', 'method' => 'POST', 'files' => true,'class' => 'col s12']) !!}
			<div class="row">
				<article id="datosNoticia" class="col s12">
					<div class="input-field col s12">
						{!! Form::text('titulo', null, ['class' => 'validate input-border-color titulo-noticia', 'placeholder' => 'Titulo de la Noticia','required']) !!}
					</div>

					<div id="resumen_noticia" class=" input-field col s12">
						<textarea id="resumen" name="resumen" class="validate materialize-textarea" data-length="155"></textarea>
						{!! Form::label('resumen', 'Resumen') !!}
					</div>
					<div class="col s12 input-field"></div>
					<div class="col s12 input-field"></div>
					<div id="texto-noticia" class=" col s8">
						<textarea id="contenido" name="contenido"></textarea>
					</div>

					<div id="imagen-carga" class=" col s4 center">
						<input name="urlImg" type="file" class="dropify" data-height="300" data-max-file-size="3M" data-allowed-file-extensions="png jpg jpeg" data-min-width="640" data-min-height="360"/>
					</div>

				</article>
			</div>
			<div class="row">
				<div class="col s12">
					<button id="btnForm" class="btn waves-effect waves-light" type="submit" name="action">Publicar Noticia</button>
				</div>
			</div>
		{!! Form::close() !!}
	</div>
	<div class="fixed-action-btn">
	    <a class="btn-floating btn-large light-blue accent-4" href="{{ url('panel/noticias') }}">
	      <i class="large material-icons">arrow_back</i>
	    </a>
	</div>
</div>

@endsection

@section('script')
	<script src="{{ asset('plugins/ckeditor/ckeditor.js') }}"></script>
	<script type="text/javascript">
		$('.dropify').dropify({
            messages: {
                'default': 'Arrastre una imagen o haga click',
                'replace': 'Arrastre una imagen o haga click para reemplazar',
                'remove':  'Remover',
                'error':   'Ooops, algo salio mal.'
            }
        });

        CKEDITOR.replace( 'contenido' );

        $(document).ready(function() {
    		$('textarea#resumen').characterCounter();
  		});

	</script>
@endsection

resources/views/panel/noticias/editar.blade.php
@extends('panel.layouts.main')

@section('titulo')
	Editar Noticia
@endsection

@section('contenido')
<div class="contenedor">
	<div class="row card center-align">
		{!! Form::open(['route' => ['noticias.update', $noticia->id], 'method' => 'PUT', 'files' => true,'class' => 'col s12']) !!}
			<div class="row">
				<article id="datosUsuario" class="col s12">
					<div class="input-field col s12">
						{!! Form::text('titulo', $noticia->titulo, ['class' => 'validate input-border-color titulo-noticia', 'placeholder' => 'Titulo de la Noticia','required']) !!}
					</div>

					<div id="resumen_noticia" class=" input-field col s12">
						<textarea id="resumen" name="resumen" class="materialize-textarea" data-length="155">{{ $noticia->resumen }}</textarea>
						{!! Form::label('resumen', 'Resumen') !!}
					</div>

					<div class="col s12 input-field"></div>
					<div class="col s12 input-field"></div>

					<div id="texto-noticia" class=" col s8">
							<textarea id="contenido" name="contenido">{{ $noticia->contenido }}</textarea>
					</div>

					<div id="imagen-carga" class=" col s4 center">
						<input name="urlImg" type="file" class="dropify" data-height="300" data-max-file-size="3M" data-allowed-file-extensions="png jpg jpeg" data-min-width="640" data-min-height="360" data-default-file="{{ url('img/noticias/' . $noticia->urlImg) }}"/>
					</div>


				</article>
			</div>
			<div class="row">
				<div class="col s12">
					<button id="btnForm" class="btn waves-effect waves-light" type="submit" name="action">Actualizar Noticia</button>
				</div>
			</div>
		{!! Form::close() !!}
	</div>
	<div class="fixed-action-btn">
	    <a class="btn-floating btn-large light-blue accent-4" href="{{ url('panel/noticias') }}">
	      <i class="large material-icons">arrow_back</i>
	    </a>
	</div>
</div>

@endsection

@section('script')
	<script src="{{ asset('plugins/ckeditor/ckeditor.js') }}"></script>
	<script type="text/javascript">
		$('.dropify').dropify({
            messages: {
                'default': 'Arrastre una imagen o haga click',
                'replace': 'Arrastre una imagen o haga click para reemplazar',
                'remove':  'Remover',
                'error':   'Ooops, algo salio mal.'
            }
        });

        CKEDITOR.replace( 'contenido' );

        $(document).ready(function() {
    		$('textarea#resumen').characterCounter();
  		});
	</script>
@endsection

resources/views/panel/noticias/index.blade.php
@extends('panel.layouts.main')

@section('titulo')
	Noticias
@endsection

@section('contenido')
<div class="contenedor">
<div class="card">
	<div class="card-content light-blue accent-4">
		<span class="card-title white-text center-align">Lista de Noticias</span>		
	</div>
	<table class="striped responsive-table">

	    <thead>
	      <tr>
			  <th></th>
	          <th>ID</th>
	          <th>Titulo</th>
	          <th>Publicado Por</th>
	          <th>Acción</th>          
	      </tr>
	    </thead>

	    <tbody>
	    	@foreach($noticias as $noticia)
	    		<tr>
	    			<td></td>
	    			<td>{{ $noticia->id }}</td>
	    			<td>{{ $noticia->titulo }}</td>
	    			<td>{{ $noticia->user->name }}</td>
	    			<td>
		    			<a href="{{ route('noticias.edit', $noticia->id) }}"><i class="material-icons">mode_edit</i></a>

		    			<a href="#!" onclick="confirmar({{ $noticia->id }}, 'noticias')"><i class="material-icons red">delete_forever</i></a>
	    			</td>
	    		</tr>
	    	@endforeach
	    </tbody>
	  </table>
      <div class="container center-align">
      	{!! $noticias->links() !!}
      </div>
      <div class="divider"></div>
 </div>
 <br>
 <div class="fixed-action-btn">
    <a class="btn-floating btn-large light-blue accent-4" href="{{ url('panel/noticias/crear') }}">
      <i class="large material-icons">add</i>
    </a>
 </div>
</div>
@endsection

@section('script')
	@include('panel.partials.sweetSure')
@endsection