routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'FrontWebController@inicio')->name('inicio');
Route::get('inicio', 'FrontWebController@inicio')->name('inicio');
Route::get('noticia/{slug}', 'FrontWebController@noticia')->name('noticia');
Route::get('zonaideal', 'FrontWebController@zonaIdeal')->name('zonaIdeal');
Route::post('documentos', 'FrontWebController@solicitudDocumentos')->name('documentos');


Route::get('nosotros', function () {
    return view('nosotros');
});

Route::get('contacto', function () {
    return view('contacto');
});

Route::middleware('auth')->prefix('panel')->group(function(){
    Route::get('/', function(){
        return view('panel.panel');
    })->name('panel.inicio');

    Route::middleware('admUsuarios')->group(function(){
        Route::resource('usuarios', 'UsersController', ['except' => [ 'show', 'destroy' ]]);
        Route::get('usuarios/{id}/eliminar', 'UsersController@destroy')->name('usuarios.destroy');

        Route::resource('slider', 'SliderController', ['only' => ['index', 'edit', 'update']]);
    });

    Route::middleware('admNoticias')->group(function(){
        Route::resource('noticias', 'NoticiasController', ['except' => [ 'show', 'destroy' ]]);
        Route::get('noticias/{id}/eliminar', 'NoticiasController@destroy')->name('noticias.destroy');
    });

    Route::middleware('admAgenda')->group(function(){
        Route::resource('agenda', 'AgendaController', ['except' => [ 'show', 'destroy' ]]);
        Route::get('agenda/{id}/eliminar', 'AgendaController@destroy')->name('agenda.destroy');
    });

    Route::middleware('admBiblioteca')->group(function(){
        Route::resource('biblioteca', 'BibliotecaController', ['except' => [ 'show', 'destroy' ]]);
        Route::get('biblioteca/{id}/eliminar', 'BibliotecaController@destroy')->name('biblioteca.destroy');
        Route::post('select-ajax', ['as'=>'select-ajax','uses'=>'BibliotecaController@selectAjax']);

        Route::resource('materias', 'MateriasController', ['except' => [ 'show', 'destroy' ]]);
        Route::get('materias/{id}/eliminar', 'MateriasController@destroy')->name('materias.destroy');
    });

    Route::get('docs', function(){
      return view('panel.documentacion');
    })->name('docs');
});

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
// Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
// Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');
Route::get('/home', 'HomeController@index')->name('home');

app/Materia.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Materia extends Model
{
    protected $table = 'materias';

    protected $fillable = ['nombre', 'nivel_id'];

    public function bibliotecas(){
        return $this->hasMany('App\Biblioteca');
    }

    public function nivel(){
    	return $this->belongsTo('App\Nivel');
    }
}

app/Http/Controllers/MateriasController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Materia;
use App\Http\Requests\MateriaRequest;

class MateriasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $materias = Materia::orderBy('id', 'ASC')->paginate(20);
        return view('panel.materias.index')->with('materias', $materias);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('panel.materias.crear');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(MateriaRequest $request)
    {
        $materia = new Materia($request->all());
        $materia->save();
        alert()->success('La materia <span class="green-text bold">'.$materia->nombre.'</span> de <span class="green-text bold">'.$materia->nivel->nombre.'</span> fue agregada', '¡Materia Agregada!')->html()->persistent();

        return redirect()->route('materias.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $materia = Materia::find($id);
        return view('panel.materias.editar')->with('materia', $materia);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(MateriaRequest $request, $id)
    {
        $materia = Materia::find($id);
        $materia->fill($request->all());
        $materia->save();

        alert()->success('La materia <span class="green-text bold">'.$materia->nombre.'</span> de <span class="green-text bold">'.$materia->nivel->nombre.'</span> fue modificada', '¡Materia Actualizada!')->html()->persistent();

        return redirect()->route('materias.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $materia = Materia::find($id);
        $materia->delete();
        alert()->error('La Materia <span class="red-text bold">'.$materia->nombre.'</span> de <span class="red-text bold">'.$materia->nivel->nombre.'</span> fue eliminada', '¡Materia Eliminada!')->html()->persistent();
        return redirect()->route('materias.index');
    }
}

resources/views/panel/materias/crear.blade.php
@extends('panel.layouts.main')

@section('titulo')
	Nueva Materias
@endsection

@section('contenido')
<div class="contenedor">
<div class="row card center-align">
	{!! Form::open(['route' => 'materias.store', 'method' => 'POST', 'class' => 'col s12']) !!}
	<div class="row">
		<article class="col s12">
			<h3>Agregar Nueva Materia</h3>
			
			<div class="input-field col s12 m12 l6">
				{!! Form::text('nombre', null, ['class' => 'validate input-border-color', 'required']) !!}
				{!! Form::label('nombre', 'Nombre de la Materia') !!}
			</div>

			<div class="input-field col s12 m12 l6">
				{!! Form::select('nivel_id', [
					'' 			=> 'Seleccione una opción',
					'Preescolar' 	=> ['1' => 'Preescolar'],
					'Primaria' 		=> [
						'2' => '1er Grado',
						'3' => '2do Grado',
						'4' => '3er Grado',
						'5' => '4to Grado',
						'6' => '5to Grado',
						'7' => '6to Grado',
					],
					'Bachillerato' 	=> [
						'8' => '1er Año',
						'9' => '2do Año',
						'10' => '3er Año',
						'11' => '4to Año',
						'12' => '5to Año',
					],
				], ['required']) !!}
				{!! Form::label('nivel_id', 'Nivel Escolar') !!}
			</div>
			<button id="btnForm" class="btn waves-effect waves-light" type="submit" name="action">Agregar Materia</button>		
		</article>
	</div>		
	{!! Form::close() !!}
</div>

<div class="fixed-action-btn">
    <a class="btn-floating btn-large light-blue accent-4" href="{{ url('panel/materias') }}">
      <i class="large material-icons">arrow_back</i>
    </a>
</div>
</div>
@endsection

@section('script')
	<script type="text/javascript">
		$(document).ready(function() {
	    	$('select').material_select();
	  	});
	</script>
@endsection

resources/views/panel/materias/editar.blade.php
@extends('panel.layouts.main')

@section('titulo')
	Editar Materia
@endsection

@section('contenido')
<div class="contenedor">
<div class="row card center-align">
	{!! Form::open(['route' => ['materias.update', $materia->id], 'method' => 'PUT', 'class' => 'col s12']) !!}
	<div class="row">
		<article class="col s12">
			<h3>Editar Materia</h3>
			
			<div class="input-field col s12 m12 l6">
				{!! Form::text('nombre', $materia->nombre, ['class' => 'validate input-border-color', 'required']) !!}
				{!! Form::label('nombre', 'Nombre de la Materia') !!}
			</div>

			<div class="input-field col s12 m12 l6">
				{!! Form::select('nivel_id', [
					'' 			=> 'Seleccione una opción',
					'Preescolar' 	=> ['1' => 'Preescolar'],
					'Primaria' 		=> [
						'2' => '1er Grado',
						'3' => '2do Grado',
						'4' => '3er Grado',
						'5' => '4to Grado',
						'6' => '5to Grado',
						'7' => '6to Grado',
					],
					'Bachillerato' 	=> [
						'8' => '1er Año',
						'9' => '2do Año',
						'10' => '3er Año',
						'11' => '4to Año',
						'12' => '5to Año',
					],
				], $materia->nivel_id ,['required']) !!}
				{!! Form::label('nivel_id', 'Nivel Escolar') !!}
			</div>
			<button id="btnForm" class="btn waves-effect waves-light" type="submit" name="action">Editar Materia</button>		
		</article>
	</div>		
	{!! Form::close() !!}
</div>

<div class="fixed-action-btn">
    <a class="btn-floating btn-large light-blue accent-4" href="{{ url('panel/materias') }}">
      <i class="large material-icons">arrow_back</i>
    </a>
</div>
</div>
@endsection

@section('script')
	<script type="text/javascript">
		$(document).ready(function() {
	    	$('select').material_select();
	  	});
	</script>
@endsection

resources/views/panel/materias/index.blade.php
@extends('panel.layouts.main')

@section('titulo')
	Materias
@endsection

@section('contenido')
<div class="contenedor">
<div class="card">
	<div class="card-content light-blue accent-4">
		<span class="card-title white-text center-align">Lista de Materias</span>		
	</div>
	<table class="striped responsive-table">

	    <thead>
	      <tr>
			  <th></th>
	          <th>ID</th>
	          <th>Materia</th>
	          <th>Nivel Escolar</th>
	          <th>Acción</th>          
	      </tr>
	    </thead>
	    <tbody>
	    	@foreach($materias as $materia)
	    		<tr>
	    			<td></td>
	    			<td>{{ $materia->id }}</td>
	    			<td>{{ $materia->nombre }}</td>
	    			<td>{{ $materia->nivel->nombre }}</td>
	    			<td>
		    			<a href="{{ route('materias.edit', $materia->id) }}"><i class="material-icons">mode_edit</i></a>

		    			<a href="#!" onclick="confirmar({{ $materia->id }}, 'materias')"><i class="material-icons red">delete_forever</i></a>
	    			</td>
	    		</tr>
	    	@endforeach
	    </tbody>
	  </table>
      <div class="container center-align">
      	{!! $materias->links() !!}
      </div>
      <div class="divider"></div>
 </div>
 <br>
 <div class="fixed-action-btn">
    <a class="btn-floating btn-large light-blue accent-4" href="{{ url('panel/materias/crear') }}">
      <i class="large material-icons">add</i>
    </a>
    <ul>
      <li><a href="{{ url('panel/biblioteca') }}" class="btn-floating green"><i class="material-icons">swap_horiz</i></a></li>
    </ul>
 </div>
</div>
@endsection