routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'FrontWebController@inicio')->name('inicio');
Route::get('inicio', 'FrontWebController@inicio')->name('inicio');
Route::get('noticia/{slug}', 'FrontWebController@noticia')->name('noticia');
Route::get('zonaideal', 'FrontWebController@zonaIdeal')->name('zonaIdeal');
Route::post('documentos', 'FrontWebController@solicitudDocumentos')->name('documentos');


Route::get('nosotros', function () {
    return view('nosotros');
});

Route::get('contacto', function () {
    return view('contacto');
});

Route::middleware('auth')->prefix('panel')->group(function(){
    Route::get('/', function(){
        return view('panel.panel');
    })->name('panel.inicio');

    Route::middleware('admUsuarios')->group(function(){
        Route::resource('usuarios', 'UsersController', ['except' => [ 'show', 'destroy' ]]);
        Route::get('usuarios/{id}/eliminar', 'UsersController@destroy')->name('usuarios.destroy');

        Route::resource('slider', 'SliderController', ['only' => ['index', 'edit', 'update']]);
    });

    Route::middleware('admNoticias')->group(function(){
        Route::resource('noticias', 'NoticiasController', ['except' => [ 'show', 'destroy' ]]);
        Route::get('noticias/{id}/eliminar', 'NoticiasController@destroy')->name('noticias.destroy');
    });

    Route::middleware('admAgenda')->group(function(){
        Route::resource('agenda', 'AgendaController', ['except' => [ 'show', 'destroy' ]]);
        Route::get('agenda/{id}/eliminar', 'AgendaController@destroy')->name('agenda.destroy');
    });

    Route::middleware('admBiblioteca')->group(function(){
        Route::resource('biblioteca', 'BibliotecaController', ['except' => [ 'show', 'destroy' ]]);
        Route::get('biblioteca/{id}/eliminar', 'BibliotecaController@destroy')->name('biblioteca.destroy');
        Route::post('select-ajax', ['as'=>'select-ajax','uses'=>'BibliotecaController@selectAjax']);

        Route::resource('materias', 'MateriasController', ['except' => [ 'show', 'destroy' ]]);
        Route::get('materias/{id}/eliminar', 'MateriasController@destroy')->name('materias.destroy');
    });

    Route::get('docs', function(){
      return view('panel.documentacion');
    })->name('docs');
});

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
// Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
// Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');
Route::get('/home', 'HomeController@index')->name('home');

app/Biblioteca.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Biblioteca extends Model
{
    protected $table = 'bibliotecas';

    protected $fillable = ['titulo', 'contenido', 'enlace', 'nivel_id', 'materia_id', 'user_id'];

    public function user(){
    	return $this->belongsTo('App\User');
    }

    public function materia(){
    	return $this->belongsTo('App\Materia');
    }

    public function nivel(){
    	return $this->belongsTo('App\Nivel');
    }

    public function scopeBuscar($query, $busqueda){
        return $query->where('titulo', 'LIKE', "%$busqueda%");
    }

    public function scopeFiltrar($query, $nivel, $materia){
        return $query->where([['nivel_id', 'LIKE', "%$nivel"], ['materia_id', 'LIKE', "%$materia"]]);
    }
}

app/Http/Controllers/BibliotecaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Biblioteca;
use App\Materia;

class BibliotecaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $materiales = Biblioteca::orderBy('id', 'ASC')->paginate(20);
        return view('panel.biblioteca.index')->with('materiales', $materiales);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('panel.biblioteca.crear');
    }

    public function selectAjax(Request $request)
    {
        if($request->ajax()){
            $materias = Materia::where('nivel_id',$request->nivel_id)->pluck("nombre","id")->all();
            $data = view('panel.biblioteca.ajax-select',compact('materias'))->render();
            return response()->json(['options'=>$data]);
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $material = new Biblioteca($request->all());
        $material->user_id = Auth::User()->id;
        $material->save();

        alert()->success('El material <span class="green-text bold">'.$material->titulo.'</span> fue agregado', '¡Material Agregado!')->html()->persistent();

        return redirect()->route('biblioteca.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $material = Biblioteca::find($id);
        return view('panel.biblioteca.editar')->with('material', $material);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $material = Biblioteca::find($id);
        $material->fill($request->all());
        $material->save();

        alert()->success('El material <span class="green-text bold">'.$material->titulo.'</span> fue agregado', '¡Material Actualizado!')->html()->persistent();

        return redirect()->route('biblioteca.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $material = Biblioteca::find($id);

        alert()->error('El material <span class="red-text bold">' . $material->titulo . '</span> fue eliminado', '¡Material Eliminado!')->html()->persistent("Ok");

        $material->delete();
        return redirect()->route('biblioteca.index');
    }
}

resources/views/panel/biblioteca/ajax-select.blade.php
<option>Seleccione materia</option>
@if(!empty($materias))
  @foreach($materias as $key => $value)
    <option value="{{ $key }}">{{ $value }}</option>
  @endforeach
@endif

resources/views/panel/biblioteca/crear.blade.php
@extends('panel.layouts.main')

@section('titulo')
	Agregar Material Biblioteca
@endsection

@section('contenido')
<div class="container">
	<div class="row card center-align">
		{!! Form::open(['route' => 'biblioteca.store', 'method' => 'POST', 'class' => 'col s12']) !!}
		<div class="row">
			<div class="input-field col s12">
				{!! Form::text('titulo', null, ['class' => 'validate input-border-color titulo-noticia', 'required']) !!}
				{!! Form::label('titulo', 'Título del Material') !!}
			</div>
			
			<br>

			<div class="col s6">
				<div class="input-field col s12">
					{!! Form::textarea('contenido', null, ['class' => 'validate materialize-textarea', 'required']) !!}
					{!! Form::label('contenido', 'Resumen del Material') !!}
				</div>
						
				<div class="input-field col s12">
					{!! Form::url('enlace', null, ['class' => 'validate', 'required']) !!}
					{!! Form::label('enlace', 'URL del Material') !!}
				</div>
			</div>
			<div class="col s6">
				<div class="input-field col s12">
					<span class="left grey-text">Nivel Escolar</span>
					{!! Form::select('nivel_id', [
						'Preescolar' 	=> ['1' => 'Preescolar'],
						'Primaria' 		=> [
							'2' => '1er Grado',
							'3' => '2do Grado',
							'4' => '3er Grado',
							'5' => '4to Grado',
							'6' => '5to Grado',
							'7' => '6to Grado',
						],
						'Bachillerato' 	=> [
							'8' => '1er Año',
							'9' => '2do Año',
							'10' => '3er Año',
							'11' => '4to Año',
							'12' => '5to Año',
						],
					], null, ['required', 'placeholder' => 'Seleccione nivel', 'class' => 'browser-default']) !!}
					
				</div>
				
				<div class="input-field col s12">
					<span class="left grey-text">Materia</span>
					{!! Form::select('materia_id', [''=>'Seleccione materia'], null, ['required', 'class' => 'browser-default']) !!}
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col s12">
				<button id="btnForm" class="btn waves-effect waves-light" type="submit" name="action">Agregar Material</button>
			</div>
		</div>
		{!! Form::close() !!}
	</div>
</div>

@endsection

@section('script')
	<script type="text/javascript">
		$(document).ready(function() {
	    	$('select').material_select();
	  	});

	  	$("select[name='nivel_id']").change(function(){
	      	var nivel_id = $(this).val();
	      	var token = $("input[name='_token']").val();
	      	$.ajax({
	          url: '../../panel/select-ajax',
	          method: 'POST',
	          data: {nivel_id:nivel_id, _token:token},
	          success: function(data) {
	            $("select[name='materia_id'").html('');
	            $("select[name='materia_id'").html(data.options);
	          }
	      	});
	  	});
	</script>
@endsection

resources/views/panel/biblioteca/editar.blade.php
@extends('panel.layouts.main')

@section('titulo')
	Editar Material Biblioteca
@endsection

@section('contenido')
<div class="container">
	<div class="row card center-align">
		{!! Form::open(['route' => ['biblioteca.update', $material->id], 'method' => 'PUT', 'class' => 'col s12']) !!}
		<div class="row">
			<div class="input-field col s12">
				{!! Form::text('titulo', $material->titulo, ['class' => 'validate input-border-color titulo-noticia', 'required']) !!}
				{!! Form::label('titulo', 'Título del Material') !!}
			</div>
			
			<br>

			<div class="col s6">
				<div class="input-field col s12">
					{!! Form::textarea('contenido', $material->contenido, ['class' => 'validate materialize-textarea', 'required']) !!}
					{!! Form::label('contenido', 'Resumen del Material') !!}
				</div>
						
				<div class="input-field col s12">
					{!! Form::url('enlace', $material->enlace, ['class' => 'validate', 'required']) !!}
					{!! Form::label('enlace', 'URL del Material') !!}
				</div>
			</div>
			<div class="col s6">
				<div class="input-field col s12">
					<span class="left grey-text">Nivel Escolar</span>
					{!! Form::select('nivel_id', [
						'Preescolar' 	=> ['1' => 'Preescolar'],
						'Primaria' 		=> [
							'2' => '1er Grado',
							'3' => '2do Grado',
							'4' => '3er Grado',
							'5' => '4to Grado',
							'6' => '5to Grado',
							'7' => '6to Grado',
						],
						'Bachillerato' 	=> [
							'8' => '1er Año',
							'9' => '2do Año',
							'10' => '3er Año',
							'11' => '4to Año',
							'12' => '5to Año',
						],
					], $material->nivel_id, ['required', 'placeholder' => 'Seleccione nivel', 'class' => 'browser-default']) !!}
					
				</div>
				
				<div class="input-field col s12">
					<span class="left grey-text">Materia</span>
					{!! Form::select('materia_id', [''=>'Seleccione materia'], null, ['required', 'class' => 'browser-default']) !!}
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col s12">
				<button id="btnForm" class="btn waves-effect waves-light" type="submit" name="action">Editar Material</button>
			</div>
		</div>
		{!! Form::close() !!}
	</div>
</div>

@endsection

@section('script')
	<script type="text/javascript">
		$(document).ready(function() {			
	    	$('select').material_select();
	  	});

	  	$("select[name='nivel_id']").change(function(){
	      	var nivel_id = $(this).val();
	      	var token = $("input[name='_token']").val();
	      	$.ajax({
	          url: '../../../panel/select-ajax',
	          method: 'POST',
	          data: {nivel_id:nivel_id, _token:token},
	          success: function(data) {
	            $("select[name='materia_id'").html('');
	            $("select[name='materia_id'").html(data.options);
	          }
	      	});
	  	}).trigger('change');
	</script>
@endsection

resources/views/panel/biblioteca/index.blade.php
@extends('panel.layouts.main')

@section('titulo')
	Biblioteca
@endsection

@section('contenido')
<div class="contenedor">
<div class="card">
	<div class="card-content light-blue accent-4">
		<span class="card-title white-text center-align">Lista de Articulos</span>		
	</div>
	<table class="striped responsive-table">

	    <thead>
	      <tr>
			  <th></th>
	          <th>ID</th>
	          <th>Titulo</th>
	          <th>Enlace</th>
	          <th>Nivel</th>
	          <th>Materia</th>
	          <th>Publicado Por</th>
	          <th>Acción</th>
	      </tr>
	    </thead>

	    <tbody>
	    	@foreach($materiales as $material)
	    		<tr>
	    			<td></td>
	    			<td>{{ $material->id }}</td>
	    			<td>{{ $material->titulo }}</td>
	    			<td>{{ $material->enlace }}</td>
	    			<td>{{ $material->nivel->nombre }}</td>
	    			<td>{{ $material->materia->nombre }}</td>
	    			<td>{{ $material->user->name }}</td>
	    			<td>
		    			<a href="{{ route('biblioteca.edit', $material->id) }}"><i class="material-icons">mode_edit</i></a>

		    			<a href="#!" onclick="confirmar({{ $material->id }}, 'biblioteca')"><i class="material-icons red">delete_forever</i></a>
	    			</td>
	    		</tr>
	    	@endforeach
	    </tbody>
	  </table>
      <div class="container center-align">
      	{!! $materiales->links() !!}
      </div>
      <div class="divider"></div>
 </div>
 <br>
 <div class="fixed-action-btn">
    <a class="btn-floating btn-large light-blue accent-4" href="{{ url('panel/biblioteca/crear') }}">
      <i class="large material-icons">add</i>
    </a>
    <ul>
      <li><a href="{{ url('panel/materias') }}" class="btn-floating green"><i class="material-icons">swap_horiz</i></a></li>
    </ul>
 </div>
</div>
@endsection

@section('script')
	@include('panel.partials.sweetSure')
@endsection