routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'FrontWebController@inicio')->name('inicio');
Route::get('inicio', 'FrontWebController@inicio')->name('inicio');
Route::get('noticia/{slug}', 'FrontWebController@noticia')->name('noticia');
Route::get('zonaideal', 'FrontWebController@zonaIdeal')->name('zonaIdeal');
Route::post('documentos', 'FrontWebController@solicitudDocumentos')->name('documentos');


Route::get('nosotros', function () {
    return view('nosotros');
});

Route::get('contacto', function () {
    return view('contacto');
});

Route::middleware('auth')->prefix('panel')->group(function(){
    Route::get('/', function(){
        return view('panel.panel');
    })->name('panel.inicio');

    Route::middleware('admUsuarios')->group(function(){
        Route::resource('usuarios', 'UsersController', ['except' => [ 'show', 'destroy' ]]);
        Route::get('usuarios/{id}/eliminar', 'UsersController@destroy')->name('usuarios.destroy');

        Route::resource('slider', 'SliderController', ['only' => ['index', 'edit', 'update']]);
    });

    Route::middleware('admNoticias')->group(function(){
        Route::resource('noticias', 'NoticiasController', ['except' => [ 'show', 'destroy' ]]);
        Route::get('noticias/{id}/eliminar', 'NoticiasController@destroy')->name('noticias.destroy');
    });

    Route::middleware('admAgenda')->group(function(){
        Route::resource('agenda', 'AgendaController', ['except' => [ 'show', 'destroy' ]]);
        Route::get('agenda/{id}/eliminar', 'AgendaController@destroy')->name('agenda.destroy');
    });

    Route::middleware('admBiblioteca')->group(function(){
        Route::resource('biblioteca', 'BibliotecaController', ['except' => [ 'show', 'destroy' ]]);
        Route::get('biblioteca/{id}/eliminar', 'BibliotecaController@destroy')->name('biblioteca.destroy');
        Route::post('select-ajax', ['as'=>'select-ajax','uses'=>'BibliotecaController@selectAjax']);

        Route::resource('materias', 'MateriasController', ['except' => [ 'show', 'destroy' ]]);
        Route::get('materias/{id}/eliminar', 'MateriasController@destroy')->name('materias.destroy');
    });

    Route::get('docs', function(){
      return view('panel.documentacion');
    })->name('docs');
});

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
// Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
// Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');
Route::get('/home', 'HomeController@index')->name('home');

resources/views/panel/usuarios/crear.blade.php
@extends('panel.layouts.main')

@section('titulo')
	Crear Usuario
@endsection

@section('contenido')
<div class="contenedor">
<div class="row card center-align">
	{!! Form::open(['route' => 'usuarios.store', 'method' => 'POST', 'class' => 'col s12']) !!}
	<div class="row">
		<article id="datosUsuario" class="col s6">
			<h3>Datos de Usuario</h3>
			
			<div class="input-field col s12">
				<i class="material-icons prefix">account_circle</i>
				{!! Form::text('name', null, ['class' => 'validate input-border-color', 'required']) !!}
				{!! Form::label('name', 'Nombre y Apellido') !!}
			</div>

			<div class="input-field col s12">
				<i class="material-icons prefix">email</i>
				{!! Form::email('email', null, ['class' => 'validate', 'required']) !!}
				{!! Form::label('email', 'Correo Electrónico') !!}
			</div>
					
			<div class="input-field col s12">
				<i class="material-icons prefix">security</i>
				{!! Form::password('password', ['class' => 'validate', 'required']) !!}
				{!! Form::label('password', 'Contraseña') !!}
			</div>
		
		</article>

		<article id="permisos" class="col s6">
			<h3>Permisos</h3>
			<div class="row">
				<div class="col s6">												
					<p>Adm. Usuario</p>
				</div>
				<div class="col s6">
					<div class="switch">
						<label>
							No
							<input type="checkbox" name="usuario" value="checked">
							<span class="lever"></span>
							Si
						</label>
					</div>
				</div>
			</div>
			<hr>

			<div class="row">
				<div class="col s6">												
					<p>Adm. Noticias</p>
				</div>
				<div class="col s6">
					<div class="switch">
						<label>
							No
							<input type="checkbox" name="noticia" value="checked">
							<span class="lever"></span>
							Si
						</label>
					</div>
				</div>
			</div>
			<hr>

			<div class="row">
				<div class="col s6">												
					<p>Adm. Agenda</p>
				</div>
				<div class="col s6">
					<div class="switch">
						<label>
							No
							<input type="checkbox" name="agenda" value="checked">
							<span class="lever"></span>
							Si
						</label>
					</div>
				</div>
			</div>
			<hr>

			<div class="row">
				<div class="col s6">												
					<p>Adm. Biblioteca</p>
				</div>
				<div class="col s6">
					<div class="switch">
						<label>
							No
							<input type="checkbox" name="biblioteca" value="checked">
							<span class="lever"></span>
							Si
						</label>
					</div>
				</div>
			</div>
			<hr>

		</article>
	</div>
	<div class="row">
		<div class="col s12">
			<button id="btnForm" class="btn waves-effect waves-light" type="submit" name="action">Crear Usuario</button>
		</div>
	</div>
	{!! Form::close() !!}
</div>

<div class="fixed-action-btn">
    <a class="btn-floating btn-large light-blue accent-4" href="{{ url('panel/usuarios') }}">
      <i class="large material-icons">arrow_back</i>
    </a>
</div>
</div>
@endsection

resources/views/panel/usuarios/editar.blade.php
@extends('panel.layouts.main')

@section('titulo')
	Editar Usuario
@endsection

@section('contenido')
<div class="contenedor">
<div class="row card center-align">
	{!! Form::open(['route' => ['usuarios.update', $usuario->id], 'method' => 'PUT', 'class' => 'col s12']) !!}
	<div class="row">
		<article id="datosUsuario" class="col s6">
			<h3>Datos de Usuario</h3>
			<br><br>
			
			<div class="input-field col s12">
				<i class="material-icons prefix">account_circle</i>
				{!! Form::text('name', $usuario->name, ['class' => 'validate input-border-color', 'required']) !!}
				{!! Form::label('name', 'Nombre y Apellido') !!}
			</div>

			<div class="input-field col s12">
				<i class="material-icons prefix">email</i>
				{!! Form::email('email', $usuario->email, ['class' => 'validate', 'required']) !!}
				{!! Form::label('email', 'Correo Electrónico') !!}
			</div>		
		</article>

		<article id="permisos" class="col s6">
			<h3>Permisos</h3>
			<div class="row">
				<div class="col s6">												
					<p>Adm. Usuario</p>
				</div>
				<div class="col s6">
					<div class="switch">
						<label>
							No
							<input type="checkbox" name="usuario" value="checked" {{ $usuario->usuario }} >
							<span class="lever"></span>
							Si
						</label>
					</div>
				</div>
			</div>
			<hr>

			<div class="row">
				<div class="col s6">												
					<p>Adm. Noticias</p>
				</div>
				<div class="col s6">
					<div class="switch">
						<label>
							No
							<input type="checkbox" name="noticia" value="checked" {{ $usuario->noticia }} >
							<span class="lever"></span>
							Si
						</label>
					</div>
				</div>
			</div>
			<hr>

			<div class="row">
				<div class="col s6">												
					<p>Adm. Agenda</p>
				</div>
				<div class="col s6">
					<div class="switch">
						<label>
							No
							<input type="checkbox" name="agenda" value="checked" {{ $usuario->agenda }} >
							<span class="lever"></span>
							Si
						</label>
					</div>
				</div>
			</div>
			<hr>

			<div class="row">
				<div class="col s6">												
					<p>Adm. Biblioteca</p>
				</div>
				<div class="col s6">
					<div class="switch">
						<label>
							No
							<input type="checkbox" name="biblioteca" value="checked" {{ $usuario->biblioteca }} >
							<span class="lever"></span>
							Si
						</label>
					</div>
				</div>
			</div>
			<hr>

		</article>
	</div>
	<div class="row">
		<div class="col s12">
			<button id="btnForm" class="btn waves-effect waves-light" type="submit" name="action">Editar Usuario</button>
		</div>
	</div>
	{!! Form::close() !!}
</div>

<div class="fixed-action-btn">
    <a class="btn-floating btn-large light-blue accent-4" href="{{ url('panel/usuarios') }}">
      <i class="large material-icons">arrow_back</i>
    </a>
</div>
</div>
@endsection

resources/views/panel/usuarios/index.blade.php
@extends('panel.layouts.main')

@section('titulo')
	Usuarios
@endsection

@section('contenido')
<div class="contenedor">
<div class="card">
	<div class="card-content light-blue accent-4">
		<span class="card-title white-text center-align">Lista de Usuarios</span>		
	</div>
	<table class="striped responsive-table">

	    <thead>
	      <tr>
			  <th></th>
	          <th>ID</th>
	          <th>Nombre</th>
	          <th>Email</th>
	          <th>Permisos</th>
	          <th>Acción</th>          
	      </tr>
	    </thead>

	    <tbody>
	    	@foreach($usuarios as $usuario)
	    		<tr>
	    			<td></td>
	    			<td>{{ $usuario->id }}</td>
	    			<td>{{ $usuario->name }}</td>
	    			<td>{{ $usuario->email }}</td>
	    			<td>
	    				<span class="hide">{!! $permisos = false !!}</span>
	    				@if($usuario->noticia == 'checked')
	    					<span class="hide">{!! $permisos = true !!}</span>
	        				<i class="fa fa-newspaper-o fa-custom2 tooltipped" data-position="top" data-delay="50" data-tooltip="Adm. Noticia"></i>
		        		@endif
		        		@if($usuario->agenda == 'checked')
		        			<span class="hide">{!! $permisos = true !!}</span>
		        			<i class="fa fa-calendar fa-custom2 tooltipped" data-position="top" data-delay="50" data-tooltip="Adm. Agenda"></i>
		        		@endif
		        		@if($usuario->biblioteca == 'checked')
		        			<span class="hide">{!! $permisos = true !!}</span>
		        			<i class="fa fa-book fa-custom2 tooltipped" data-position="top" data-delay="50" data-tooltip="Adm. Biblioteca"></i>
		        		@endif
		        		@if($usuario->usuario == 'checked')
		        			<span class="hide">{!! $permisos = true !!}</span>
		        			<i class="fa fa-users fa-custom2 tooltipped" data-position="top" data-delay="50" data-tooltip="Adm. Usuario"></i>
		        		@endif
		        		@if($permisos == false)
		        			Usuario sin permisos
		        		@endif
	    			</td>
	    			<td>
		    			<a href="{{ route('usuarios.edit', $usuario->id) }}"><i class="material-icons">mode_edit</i></a>

		    			<a href="#!" onclick="confirmar({{ $usuario->id }}, 'usuarios')"><i class="material-icons red">delete_forever</i></a>
	    			</td>
	    		</tr>
	    	@endforeach
	    </tbody>
	  </table>
      <div class="container center-align">
      	{!! $usuarios->links() !!}
      </div>
      <div class="divider"></div>
 </div>
 <br>
 <div class="fixed-action-btn">
    <a class="btn-floating btn-large light-blue accent-4" href="{{ url('panel/usuarios/crear') }}">
      <i class="large material-icons">add</i>
    </a>
    <ul>
      <li><a href="{{ url('panel/slider') }}" class="btn-floating green"><i class="material-icons">swap_horiz</i></a></li>
    </ul>
 </div>
</div>
@endsection

@section('script')
	@include('panel.partials.sweetSure')
@endsection